object MasterState extends Enumeration {
    type MasterState = Value
    val SERVER_START, SERVER_FINISH,
    CONNECTION_START, CONNECTION_FINISH,
    SAMPLING_START, SAMPLING_PIVOT, SAMPLING_FINISH,
    SORT_PARTITION_START, SORT_PARTITION_FINISH,
    SHUFFLE_START, SHUFFLE_FINISH,
    MERGE_START, MERGE_FINISH = Value
}
