object WorkerState extends Enumeration {
    type WorkerState = Value
    val CONNECTION_START, CONNECTION_FINISH,
    SAMPLING_START, SAMPLING_FINISH,
    SORT_PARTITION_START, SORT_PARTITION_FINISH,
    SHUFFLE_START, SHUFFLE_FINISH,
    MERGE_START, MERGE_FINISH = Value
}
